/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.psa.controller;import cn.zhuatech.psa.common.ApiResponse;import cn.zhuatech.psa.service.ProjectFinancialClosureService;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                             */
@RestController @RequestMapping("/api/enterprise/psa")public class ProjectFinancialClosureController{private final ProjectFinancialClosureService service;/**
                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                       */
public ProjectFinancialClosureController(ProjectFinancialClosureService service){this.service=service;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
@PostMapping("/project-financial-closure")public ApiResponse<ProjectFinancialClosureService.Assessment>assess(@Valid @RequestBody ProjectFinancialClosureService.Request request){return ApiResponse.ok(service.assess(request));}}
