/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.psa.service;import org.junit.jupiter.api.Test;import static org.assertj.core.api.Assertions.assertThat;/**
                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                            */
class ProjectFinancialClosureServiceTest{private final ProjectFinancialClosureService service=new ProjectFinancialClosureService();/**
                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                               */
@Test void closesFinanciallyCompleteProject(){var r=service.assess(new ProjectFinancialClosureService.Request("P1",true,true,true,true,true,0,0,true));assertThat(r.decision()).isEqualTo(ProjectFinancialClosureService.Decision.CLOSE);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         */
@Test void blocksUnfinishedFinancialControls(){var r=service.assess(new ProjectFinancialClosureService.Request("P2",false,false,false,false,false,2,0,true));assertThat(r.blockers()).hasSize(6);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
@Test void reviewsWipAndLessons(){var r=service.assess(new ProjectFinancialClosureService.Request("P3",true,true,true,true,true,0,1000,false));assertThat(r.actions()).hasSize(2);}}
