/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.psa.service;import jakarta.validation.constraints.Min;import jakarta.validation.constraints.NotBlank;import org.springframework.stereotype.Service;import java.util.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Service public class ProjectFinancialClosureService{/**
                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                      */
public Assessment assess(Request r){List<String>b=new ArrayList<>(),a=new ArrayList<>();if(!r.timeApproved())b.add("项目工时尚未全部审批");if(!r.expensesReconciled())b.add("费用尚未对账");if(!r.billingComplete())b.add("应开票里程碑尚未完成");if(!r.revenueRecognitionApproved())b.add("收入确认尚未批准");if(!r.customerAcceptanceRecorded())b.add("客户验收证据缺失");if(r.openChangeOrders()>0)b.add("存在未关闭的变更单");if(!b.isEmpty()){a.add("阻止财务结项并关闭工时、费用、开票、收入和变更问题");return new Assessment(Decision.BLOCKED,b,a);}if(r.unbilledWipCents()>0||!r.lessonsLearnedRecorded()){if(r.unbilledWipCents()>0)a.add("处理未开票在制品余额");if(!r.lessonsLearnedRecorded())a.add("完成项目复盘与经验归档");return new Assessment(Decision.REVIEW,b,a);}a.add("关闭项目财务期间并冻结毛利与交付证据");return new Assessment(Decision.CLOSE,b,a);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
public record Request(@NotBlank String projectCode,boolean timeApproved,boolean expensesReconciled,boolean billingComplete,boolean revenueRecognitionApproved,boolean customerAcceptanceRecorded,@Min(0)int openChangeOrders,@Min(0)long unbilledWipCents,boolean lessonsLearnedRecorded){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
public record Assessment(Decision decision,List<String>blockers,List<String>actions){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
public enum Decision{CLOSE,REVIEW,BLOCKED}}
